### ISSUE TITLE
Calling 'pdfschedule' correctly

### ISSUE THREAD

**Issue by iaverypadberg** [jwodder/schedule#1]
Hi- I found your scheduling library and though it looked useful. I am still confused on how to call the pdfschedule function  properly... could you send a screen shot or a better description? 

Thanks

**Comment by jwodder** [comment]
`pdfschedule` is intended to be used as a command-line program run from the command line (i.e., via Terminal in macOS/Linux or via the Command Prompt or whatever it's called in Windows), not as a library function.  An example invocation would look like:

```
pdfschedule --font Courier --color input_filename.yaml output_filename.pdf
```

where the file `input_filename.yaml` is a YAML file containing data structured as described under "Input Format" in the README.

If you really want to use `pdfschedule` as a library instead, the way to do it is as follows (Note that I want to change & improve some of this in various ways, which is why it isn't documented yet, but don't hold your breath on the changes being released anytime soon):

* Create a `pdfschedule.Schedule` object with a statement like `sched = Schedule(week)` where `week` is a list of weekday names to display at the top of the schedule.  `pdfschedule` provides three constants for use as the `week` value: `WEEKDAYS_EN` (`"Monday"` through `"Friday"`), `FULL_WEEK_EN` (`"Sunday"` through `"Saturday"`), and `FULL_WEEK_MON_EN` (`"Monday"` through `"Sunday"`).

* For each event you want to show on the schedule, create a `pdfschedule.Event` object with the following parameters:

    * `start_time` — a `datetime.time`
    * `end_time` — a `datetime.time`
    * `text` — a list of lines to show in the event's box
    * `color` — a triple of floats in the range 0 to 1 giving the RGB components of the color to use for the background of the event's box
    * `days` — a list of days of the week on which the event occurs, spelled the same way as in the `week` argument to the `Schedule` constructor

    Then add the event to the `Schedule` object with `sched.add_event(event)`.

* Create a `reportlab.pdfgen.canvas.Canvas` object with a statement like `c = Canvas(outfile_path, (page_width, page_height))`

* Set the canvas's font with `c.setFont(font_name, font_size)`

* Call the `sched.render()` method of the `Schedule` with the following arguments:

    * the `Canvas` object (as the first argument)
    * `x` — the distance (in Reportlab's units; points, I believe) between the left edge of the page and the left edge of the displayed schedule
    * `y` — the distance between the top of the page and the top edge of the displayed schedule
    * `width` — the width of the box in which to display the schedule
    * `height` — the height of the box in which to display the schedule
    * `font_size` — the font size to use for displaying text in event boxes (This should be the same value as passed to `setFont()` above)
    * `show_times` — true if the times should be shown along the left side of the schedule, false to not show them

* Finally, call `c.showPage()` and `c.save()` to write the rendered schedule as a PDF to `outfile_path`.

**Comment by iaverypadberg** [comment]
Hi John-

Thanks for the explanation, I am going to opt for the the terminal command
as it is certainly easier to work with.

Cheers!
Isaac A-p
